on: pull_request

permissions: write-all

jobs:
  t:
    environment:
      name: "PUBLIC"
      url: "javascript://alert(1)"
      deployment: false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged: ${{ secrets.FLAG }}
